version: '3.1'
services:
  app_container:
    image: 'tenpo:latest'
    build:
      context: .
    container_name: api-tenpo
    restart: always
    ports:
     - "8888:8080"
    depends_on:
      - database_container
  database_container:
    image: postgres
    ports:
     - "5555:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=tenpo
      - POSTGRES_HOST_AUTH_METHOD=trust