version: '3.1'
services:
  app_container:
    image: 'tenpo:latest'
    build:
      context: .
    container_name: api-tenpo
    restart: unless-stopped
    ports:
     - "8888:8080"
    depends_on:
      - db
    env_file:
      - config_docker.env
  db:
    container_name: db
    image: postgres
    ports:
     - "5432"
    env_file:
    - config_docker.env