version: '3.1'

services:
  app:
    image: 'tenpo:latest'
    build:
      context: .
    container_name: api-tenpo
    ports:
     - "8888:8080"
  # depends_on:
    #  - database
     #database:
     #image: postgres
       #ports:
     #- "5555:5432"
       #environment:
       # - POSTGRES_PASSWORD=root
       # - POSTGRES_USER=root
     # - POSTGRES_DB=tenpo
     # - POSTGRES_HOST_AUTH_METHOD=trust